/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.20
 * Generated at: 2022-04-29 03:51:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import java.io.*;
import java.time.*;
import indexer.Indexer;
import engine.SearchEngine;
import repository.Repository;
import model.RetrievedDocument;

public final class SearchPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.time");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("repository.Repository");
    _jspx_imports_classes.add("model.RetrievedDocument");
    _jspx_imports_classes.add("engine.SearchEngine");
    _jspx_imports_classes.add("indexer.Indexer");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("		<title> &nbsp;&nbsp; Google </title>\n");
      out.write("		\n");
      out.write("		<link rel=\"stylesheet\" href=\"stylesheets/reset.css\">\n");
      out.write("		<link rel=\"stylesheet\" href=\"stylesheets/styles.css\">\n");
      out.write("	</head>\n");
      out.write("	\n");
      out.write("	<body>\n");
      out.write("		<div id=\"header\">\n");
      out.write("			<div id=\"logoWrapper\">\n");
      out.write("				<div id=\"logo\" onclick=\"window.location='/'\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		\n");
      out.write("			<div id=\"searchQueryWrapper\">\n");
      out.write("				<div id=\"searchForm\">\n");
      out.write("                        <!-- PrintWriter out = res.getWriter();  -->\n");
      out.write("					<form action=\"SearchPage.jsp\" method=\"get\">\n");
      out.write("                        ");

                        String yes = request.getParameter("search_query");

                        out.println("<input type='text' name='search_query' id='searchQuery' value=' " + yes + "'>");
                        
      out.write("\n");
      out.write("                        <button type='submit' id='submit'></button>\n");
      out.write("					</form>\n");
      out.write("					<div id=\"searchIcon\"></div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div id=\"headerRight\">\n");
      out.write("				<div id=headerRightContent>\n");
      out.write("					<!-- <a href=\"#\"><span>+user</span></a>&nbsp;&nbsp;&nbsp;  -->\n");
      out.write("					<div id=\"apps\">&nbsp;</div>&nbsp;&nbsp;&nbsp;\n");
      out.write("					<div id=\"notifications\">&nbsp;</div>&nbsp;&nbsp;&nbsp;\n");
      out.write("					<div id=\"googleShare\">&nbsp;</div>&nbsp;&nbsp;&nbsp;\n");
      out.write("					<div id=\"dp\">&nbsp;</div>	\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	 \n");
      out.write("		 <div id=\"searchOptions\">\n");
      out.write("			<div id=\"bottomLine\">\n");
      out.write("			</div>\n");
      out.write("			<div id=\"placeholder\">\n");
      out.write("			</div>\n");
      out.write("			<div id=\"soWeb\">\n");
      out.write("				Web\n");
      out.write("			</div>\n");
      out.write("		 </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("		 \n");
      out.write("\n");
      out.write("         ");

String query = request.getParameter("search_query");

// do stuff

if (query != null){
		Instant before = Instant.now();
    Repository.openConnections();
    List<RetrievedDocument> results = SearchEngine.processQuery(query);
		Instant after = Instant.now();
		long delta = Duration.between(before, after).toMillis(); 
		String output = "About "+ results.size() +" results ( "+ ((float)delta / 1000.0) + " seconds)";
	
			out.println("<div id='searchInfo'><span>" + output + "</span></div>");
	
    for(int i = 0; i < results.size(); i++){
        out.println(results.get(i).htmlString());
    }

    Repository.closeAllConnections();
}
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 		 \n");
      out.write("		 <div id=\"searchResults\">\n");
      out.write("			<div class=\"resultWrapper\">\n");
      out.write("				<div class=\"heading\">\n");
      out.write("					<a href=\"#\">Is there a working sample of the google custome search rest... </a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"url\">\n");
      out.write("					stackoverflow.com/.../is-there-a-working-sample-of-the-google-custome-...\n");
      out.write("				</div>\n");
      out.write("				<div class=\"content\">\n");
      out.write("				<span class=\"date\">\n");
      out.write("					Mar 6, 2014 -\n");
      out.write("				</span>\n");
      out.write("					 The place to start with rest api is here: https://developers.google.com/custom-search/json-api/v1/introduction. Example: &lt;div id=\"content\"&gt;&lt;/div&gt; ...\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"resultWrapper\">\n");
      out.write("				<div class=\"heading\">\n");
      out.write("					<a href=\"#\">Send a Sample Request - Google Developers </a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"url\">\n");
      out.write("					https://developers.google.com/doubleclick-search/v2/requests\n");
      out.write("				</div>\n");
      out.write("				<div class=\"content\">\n");
      out.write("				<span class=\"date\">\n");
      out.write("					Sep 16, 2014 -\n");
      out.write("				</span>\n");
      out.write("					After you've set everything up, make sure you can successfully send a sample request to the DoubleClick Search API. The following code ...\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"resultWrapper\">\n");
      out.write("				<div class=\"heading\">\n");
      out.write("					<a href=\"#\">Code Samples - Google Maps JavaScript API v3 - Google ... </a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"url\">\n");
      out.write("					https://developers.google.com/maps/documentation/javascript/examples/\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<div class=\"content\">\n");
      out.write("				<span class=\"date\">\n");
      out.write("				</span>\n");
      out.write("					 All of the examples contained in the Google Maps JavaScript API ... details . Place search pagination . Search for up to 200 places with Radar Search . Place ... \n");
      out.write("					 Simple Map - Geolocation - Simple markers - Localizing the Map\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"resultWrapper\">\n");
      out.write("				<div class=\"heading\">\n");
      out.write("					<a href=\"#\">YouTube Data API: Python Code Samples - Google </a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"url\">\n");
      out.write("					https://developers.google.com/youtube/v3/code_samples/python\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<div class=\"content\">\n");
      out.write("				<span class=\"date\">\n");
      out.write("				</span>\n");
      out.write("					 The following code samples, which use the Google APIs Client Library ... Search by keyword ( search.list ); Search by topic ( search.list ); Add a ...\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"resultWrapper\">\n");
      out.write("				<div class=\"heading\">\n");
      out.write("					<a href=\"#\">Sample Extensions - Google Chrome </a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"url\">\n");
      out.write("					https://developer.chrome.com/extensions/samples\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<div class=\"content\">\n");
      out.write("				<span class=\"date\">\n");
      out.write("					Jun 5, 2014 -\n");
      out.write("				</span>\n");
      out.write("					 My Bookmarks. A browser action with a popup dump of all bookmarks, including search, add, edit and delete. Calls: ... Context Menus Sample (with Event Page).\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"resultWrapper\">\n");
      out.write("				<div class=\"heading\">\n");
      out.write("					<a href=\"#\">About Samples for Google App Engine - Google Code </a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"url\">\n");
      out.write("					code.google.com/p/google-app-engine-samples/\n");
      out.write("				</div>\n");
      out.write("				<div class=\"content\">\n");
      out.write("				<span class=\"date\">\n");
      out.write("				</span>\n");
      out.write("					 About Samples for Google App Engine. This project contains code for sample applications that run on Google App Engine. All samples ... search, browse source.\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"resultWrapper\">\n");
      out.write("				<div class=\"heading\">\n");
      out.write("					<a href=\"#\">Google Custom Search Sample Code / Forums / Community /... </a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"url\">\n");
      out.write("					https://ellislab.com/forums/viewthread/242368/\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<div class=\"content\">\n");
      out.write("				<span class=\"date\">\n");
      out.write("					Jan 27, 2014 - 3 posts - 3 authors<br />\n");
      out.write("				</span>\n");
      out.write("					 Does anyone have sample code for integrating google custom search into expression engine? essentially. 1. you have a search field 2. enter ...\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"resultWrapper\">\n");
      out.write("				<div class=\"heading\">\n");
      out.write("					<a href=\"#\">Google Maps Sample Project | Getting started - SoapUI </a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"url\">\n");
      out.write("					www.soapui.org &gt; Documentation &gt; Getting started &gt; API Sample Projects\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<div class=\"content\">\n");
      out.write("				<span class=\"date\">\n");
      out.write("				</span>\n");
      out.write("					 The sample project for the Google Maps defines a number of requests for each of ... Nearby Search Sample: Performs a nearby search with given coordinates ...\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"resultWrapper\" id=\"last\">\n");
      out.write("				<div class=\"heading\">\n");
      out.write("					<a href=\"#\">Quickstart - CasperJS 1.1.0-DEV documentation </a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"url\">\n");
      out.write("					casperjs.readthedocs.org/en/latest/quickstart.html\n");
      out.write("				</div>\n");
      out.write("				<div class=\"content\">\n");
      out.write("				<span class=\"date\">\n");
      out.write("				</span>\n");
      out.write("					 In the following example, we'll query google for two terms consecutively, ... casper.start('http://google.fr/', function() { // search for 'casperjs' from google form ...\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		 </div>\n");
      out.write("		  -->\n");
      out.write("		 <!-- <div id=\"relatedSearches\">\n");
      out.write("			<hr />\n");
      out.write("			<div>\n");
      out.write("				<span id=\"relatedSearchesHead\">\n");
      out.write("					Searches related to sample google search<br />\n");
      out.write("				</span>\n");
      out.write("				\n");
      out.write("				<a href=\"#\">sample google <b>forms education</b></a>\n");
      out.write("				<br />\n");
      out.write("				<a href=\"#\">sample google <b>docs spreadsheet</b></a>\n");
      out.write("				<br/>\n");
      out.write("				<a href=\"#\">google <b>docs questionnaire template</b></a>\n");
      out.write("			</div>\n");
      out.write("			<hr />\n");
      out.write("		 </div>\n");
      out.write("		 \n");
      out.write("		 <div id=\"pageNo\">\n");
      out.write("			<div id=\"pageNoInside\">\n");
      out.write("				 <div id=\"Go\"></div>\n");
      out.write("				 <a href=\"#\"><div class=\"o\"></div></a>\n");
      out.write("				 <a href=\"#\"><div class=\"o\"></div></a>\n");
      out.write("				 <a href=\"#\"><div class=\"o\"></div></a>\n");
      out.write("				 <a href=\"#\"><div class=\"o\"></div></a>\n");
      out.write("				 <a href=\"#\"><div class=\"o\"></div></a>\n");
      out.write("				 <a href=\"#\"><div class=\"o\"></div></a>\n");
      out.write("				 <a href=\"#\"><div class=\"o\"></div></a>\n");
      out.write("				 <a href=\"#\"><div class=\"o\"></div></a>\n");
      out.write("				 <a href=\"#\"><div class=\"o\"></div></a>\n");
      out.write("				 <a href=\"#\"><div id=\"gle\"></div></a>\n");
      out.write("				 <a href=\"#\"><a href=\"#\"><div id=\"rightArrow\"></div></a>\n");
      out.write("			 </div>\n");
      out.write("			 <div id=\"pageDigits\">\n");
      out.write("				<span><b>1</b></span> <a href=\"#\"><span>2</span></a> <a href=\"#\"><span>3</span></a> <a href=\"#\"><span>4</span></a> <a href=\"#\"><span>5</span></a> <a href=\"#\"><span>6</span></a> <a href=\"#\"><span>7</span></a> <a href=\"#\"><span>8</span></a> <a href=\"#\"><span>9</span></a> <a href=\"#\"><span>10</span></a> <a href=\"#\"><span id=\"next\">Next</span></a>\n");
      out.write("			 </div>\n");
      out.write("		</div> -->\n");
      out.write("		 \n");
      out.write("		<div id=\"footer\">\n");
      out.write("			<a href=\"#\"><span id=\"help\">Help</span></a> <a href=\"#\"><span>Send feedback</span></a> <a href=\"#\"><span>Privacy</span></a> <a href=\"#\"><span>Terms</span></a>\n");
      out.write("		</div>\n");
      out.write("	</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
